name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          cd ./database
          touch .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_URI=${{ secrets.POSTGRES_URI }} >> .env

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
        # Start PostgreSQL service
      - name: Start PostgreSQL
        run: |
          sudo service postgresql start

      - name: Create PostgreSQL Database
        run: |
          sudo -u postgres createdb csye6225

      - name: Change password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

      - name: Install Dependencies
        run: |
          cd ./database && npm install
          cd ../server && npm install
        # Add more steps here for your project's setup

      - name: Run Integration Tests
        run: |
          pwd
          cd ./database && npm run test
